apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-blobfuse-models
spec:
  storageClassName: azureblob-fuse-premium
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-blobfuse-models
