# Local alternative to Blob PV
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-models
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
