# Local alternative to Blob PV
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-models
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: pv-models