kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-blobnfs-models
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-blobnfs-models
  storageClassName: azureblob-nfs-premium