apiVersion: apps/v1
kind: Deployment
metadata:
  name: cv-deployment
  labels:
    app: cv-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cv-app
  template:
    metadata:
      labels:
        app: cv-app
    spec:
      # restartPolicy: OnFailure
      containers:
        - name: cv-inference
          image: yeruhero/yolov3api:latest
          ports:
            - containerPort: 5000
          imagePullPolicy: IfNotPresent
          # resources:
          #   limits:
          #     nvidia.com/gpu: 1
          # tolerations:
          #   - key: nvidia.com/gpu
          #     operator: Exists
          #     effect: NoSchedule
        - name: cv-worker
          image: yeruhero/cv-worker:latest
          ports:
            - containerPort: 9300
          imagePullPolicy: IfNotPresent
