apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-blobnfs-models
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azureblob-nfs-premium
  csi:
    driver: blob.csi.azure.com
    readOnly: false
    volumeHandle: realtimecv#rcvblobs#trained-model
    volumeAttributes:
      resourceGroup: realtimecv
      storageAccount: rcvblobs
      containerName: trained-model
      protocol: nfs