<script setup lang="ts">
</script>

<template>
  <div class="spinner-wrap">
    <div class="spinner">
      <div></div><div></div><div></div>
    </div>
  </div>
</template>

<style scoped>
  @keyframes ldio-h1hzbey605r-1 {
    0% { top: 18px; height: 64px }
    50% { top: 30px; height: 40px }
    100% { top: 30px; height: 40px }
  }
  @keyframes ldio-h1hzbey605r-2 {
    0% { top: 20.999999999999996px; height: 58.00000000000001px }
    50% { top: 30px; height: 40px }
    100% { top: 30px; height: 40px }
  }
  @keyframes ldio-h1hzbey605r-3 {
    0% { top: 24px; height: 52px }
    50% { top: 30px; height: 40px }
    100% { top: 30px; height: 40px }
  }
  .spinner div { position: absolute; width: 15px }.spinner div:nth-child(1) {
                                                             left: 17.5px;
                                                             background: #bbbbbb;
                                                             animation: ldio-h1hzbey605r-1 1s cubic-bezier(0,0.5,0.5,1) infinite;
                                                             animation-delay: -0.2s
                                                           }
  .spinner div:nth-child(2) {
    left: 42.5px;
    background: #bbbbbb;
    animation: ldio-h1hzbey605r-2 1s cubic-bezier(0,0.5,0.5,1) infinite;
    animation-delay: -0.1s
  }
  .spinner div:nth-child(3) {
    left: 67.5px;
    background: #bbbbbb;
    animation: ldio-h1hzbey605r-3 1s cubic-bezier(0, 0.5, 0.5, 1) infinite;
  }

  .spinner-wrap {
    width: 44px;
    height: 44px;
    display: inline-block;
    overflow: hidden;
    background: none;
  }
  .spinner {
    width: 100%;
    height: 100%;
    position: relative;
    transform: translateZ(0) scale(0.44);
    backface-visibility: hidden;
    transform-origin: 0 0; /* see note above */
  }
  .spinner div { box-sizing: content-box; }
  /* generated by https://loading.io/ */
</style>