name: Deploy Azure Function App & Resources

on:
  push:
    branches: ["master"]

env:
  AZURE_RESOURCE_GROUP: 'JeroenBol'
  AZURE_FUNCTIONAPP_NAME: 'jbㅊㅍfunctions'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'backend/src/RealtimeCv.Functions'
  UNIT_TESTS_PACKAGE_PATH: 'backend/tests/RealtimeCv.UnitTests'
  BICEP_PATH: 'template.bicep'
  DOTNET_VERSION: '7.0.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Checkout code'
      uses: actions/checkout@v3

#     - name: 'Login via Azure CLI'
#       uses: azure/login@v1
#       with:
#         creds: ${{ secrets.AZURE_CREDENTIALS }}

#     - name: Deploy Bicep Template
#       uses: azure/CLI@v1
#       with:
#         azcliversion: 2.30.0
#         inlineScript: |
#           az deployment group create \
#             --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
#             --template-file ${{ env.BICEP_PATH }} \
#             --parameters location=westeurope \
#                          storageAccountName=triplejbstorage \
#                          sqlServerName=triplejbdbserver \
#                          sqlDatabaseName=tripjedbdb \
#                          blobContainerNameModel=trained-model \
#                          queueNameStreamPollChunk=stream-poll-chunk \
#                          functionAppName=triplejbfunctions \
#                          webPubSubName=triplejbpubsub \
#                          sqlServerAdminLogin=admin \
#                          sqlServerAdminLoginPassword=${{ secrets.SQL_SERVER_ADMIN_PASSWORD }}

    - name: 'Setup .NET ${{ env.DOTNET_VERSION }}'
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Build Functions'
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build --configuration Release --output ./output
        popd
        
    - name: 'Test .NET'
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet test --no-build
        popd

    - name: 'Deploy Functions'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        slot-name: 'production' 
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
        
